-- Moderaty — YouTube Comment Auto-Moderation Tool
-- Copyright (C) 2026 Andrew Philip Weilbacher
--
-- Licensed under the PolyForm Shield License 1.0.0; you may not use
-- this file except in compliance with the License. You may obtain a
-- copy of the License at <https://polyformproject.org/licenses/shield/1.0.0>.
--
-- The software is provided "as is", without warranty or condition of
-- any kind, express or implied. See the License for the specific
-- language governing permissions and limitations under the License.
-- A copy of the License is included in the LICENSE file at the
-- repository root.
--
-- Commercial licensing: contact@marketingprowess.simplelogin.com — see COMMERCIAL.md

-- Issue #77: the dashboard ban counter (action='ban' + channel_id IN,
-- GROUP BY channel_id) and the per-channel log page (channel_id =) both
-- full-scan audit_log, which grows with every moderation decision. The
-- composite serves the ban query; its leftmost column serves channel-only
-- reads. Expand-only (I7): index creation touches no rows.
CREATE INDEX `audit_log_channel_action_idx` ON `audit_log` (`channel_id`,`action`);
